linking_gen_script: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/tools_custom/linking_gen.py
dataset_divider_script: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/tools_custom/gen_ocr_train_val_test.py
trainer_script: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/tools/train.py
export_model_script: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/tools/export_model.py
predict_script: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/ppstructure/kie/predict_kie_token_ser_re.py
predict_ser_script: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/ppstructure/kie/predict_kie_token_ser.py
infer_script: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/tools/infer_kie_token_ser_re.py
infer_ser_script: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/tools/infer_kie_token_ser.py
rec_gt_gen_script: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/tools_custom/gen_rec_gt.py
visual_font: /home/philgun/Documents/sribuu/ocr/paddle-ocr-sribuu/tools_custom/fonts/simfang.ttf
algorithm_ser: algorithm_ser.yml
algorithm_re: algorithm_re.yml
